### ISSUE TITLE
Network error after lauching adguardhome with podman

### ISSUE THREAD

**Issue by Al4ndil** [whi-tw/macvlan-unifi-udr#11]
Hi,
After running macvlan-unify-udr and try lauching adguardhome, i have : 
`Error: unable to find network configuration for dns: network not found`
And if i use the command
`zgrep CONFIG_MACVLAN /proc/config.gz`
i have
`# CONFIG_MACVLAN is not set`
UDR firmware 3.0.13

**Comment by whi-tw** [comment]
So the zgrep command is a bit of a red herring when using this repo - that only shows the state of built-in modules.

Can you provide the output of `lsmod | grep macvlan`?

I presume you have done *everything* from the adguardhome instructions, now you have the module installed? It sounds like you may have missed the step where you create the CNI network.

I'm not able to get onto my UDR at the moment, but I know that mine is working a-ok ever since I got the macvlan module loaded.

**Comment by whi-tw** [comment]
The first couple of steps in this readme: https://github.com/unifi-utilities/unifios-utilities/blob/main/AdguardHome/README.md

Make sure you have also run the on boot scripts. 

We're at the end of the line here though - your screenshot shows the module is loaded, so there's nothing more I can really do to help you.

The steps on the unifios-utilities repo got me to a working setup, so they should also get you there if you make sure you've done everything correctly.

Potentially reboot your UDR?

**Comment by Al4ndil** [comment]
I did all steps once again... Don't work... but ! with the command netstat -r, i have : 
[https://i.imgur.com/poBWj6h.png](url)
I think Genmask is my problem... Isn't it ?

**Comment by whi-tw** [comment]
Honestly, I really don't know. It looks like the `macvlan` module has loaded properly, so I can't really help more.

Maybe the folks on Reddit [/r/Ubiquiti](https://www.reddit.com/r/ubiquiti) or the [Unofficial Discord](https://discord.com/invite/4eugGBz) can help you further!

**Comment by whi-tw** [comment]
> [https://i.imgur.com/poBWj6h.png](url)

FYI: to make a link properly, the syntax is: `[text to show](https://url.to.link.to)`
